routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome')->middleware('guest');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth', 'verified']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('posts', 'PostController');
    Route::post('posts/{post}/comment', 'PostController@addComment')->name('comments.store');
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['comment', 'parent_id'];

    /**
     * Comment belongs to a user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'banner_image'];

    /**
     * Get the banner image url for this post.
     *
     * @return \Illuminate\Contracts\Routing\UrlGenerator|string
     */
    public function bannerImageUrl()
    {
        $path = getPostBannerConfig('link_path') . DIRECTORY_SEPARATOR . $this->banner_image;
        return url($path);
    }

    /**
     * Show page url for this post.
     *
     * @return string
     */
    public function showPageUrl()
    {
        return route('posts.show', ['post' => $this->id]);
    }

    /**
     * Post belongs to a user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Post has many comments.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * User has many posts.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\PostCreateRequest;
use App\Http\Resources\Post as PostResource;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Throwable;

class PostController extends Controller
{
    /**
     * Get the paginated post details for feeds.
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function index()
    {
        $posts = Post::with('user')->latest()->paginate(10);
        return PostResource::collection($posts);
    }

    /**
     * Create page for creating a post.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     *  Store a post.
     *
     * @param PostCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PostCreateRequest $request)
    {
        try {
            DB::beginTransaction();
            $input = $request->only('title', 'description');
            $extension = $request->file('banner_image')->getClientOriginalExtension();
            $fileName = 'image' . time() . random_int(1111, 9999) . '.' . $extension;
            $request->file('banner_image')->storeAs(getPostBannerConfig('storage_path'), $fileName);
            $input['banner_image'] = $fileName;
            auth()->user()->posts()->create($input);
            DB::commit();

            return redirect()->route('home')->withStatus('Your post has been published!');
        } catch (Throwable $throwable) {
            DB::rollBack();
            logError('Error occurred while storing a post', 'PostController@store', $throwable, [
                'input' => $request->all(),
            ]);
            return redirect()->back()->withInput()->withError('Unable to post now. Please try again later!');
        }
    }

    /**
     * Show the requested post.
     *
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Post $post)
    {
        $post->load('comments.user');
        $comments = ['base' => []];
        if ($post->comments->isNotEmpty()) {
            $comments = $post->comments->groupBy('parent_id');
            $comments['base'] = $comments[''];
            unset($comments['']);
        }

        return view('posts.show', compact('post', 'comments'));
    }

    /**
     * Add comment for the requested post.
     *
     * @param Post $post
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function addComment(Post $post, Request $request)
    {
        if (!$request->input('comment')) {
            return redirect()->route('posts.show', $post)->withError('Please type some comment to reply!');
        }

        $comment = new Comment($request->only('comment', 'parent_id'));
        $comment->user_id = auth()->id();
        $post->comments()->save($comment);
        return redirect()->route('posts.show', $post)->withStatus('Comment added successfully!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Feeds')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8" id="dashboard">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <div id="feeds">
                    {{-- Feeds goes here..! --}}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        let initial = true;
        let getPostUrl = '{{ route('posts.index') }}' + '?page=1';

        $(document).ready(function(){
            loadPosts();
        });


        function loadPosts() {
            if (getPostUrl == null) {
                $('#load-more').html('<p class="text-muted">You caught up everything..!</p>');
                return;
            }
            $.ajax({
                type: 'GET',
                url: getPostUrl,
                success: function (data) {
                    let responseData = JSON.parse(JSON.stringify(data));
                    $.each(responseData.data, function (key, post) {
                        $('#feeds').append(
                            `<div class="card mb-4">
                                <a href="${post.show_page_url}" class="card-link text-black-primary">
                                    <img class="card-img-top" src="${post.banner_image_url}" alt="Post banner image">
                                </a>
                                <div class="card-body">
                                    <h5 class="card-title"><a href="${post.show_page_url}" class="card-link text-black-primary">${post.title}</a></h5>
                                    <h6 class="card-subtitle mb-3"><a href="javascript:void(0)" class="card-link">${post.user.name}</a></h6>
                                    <p class="card-text">${post.description}</p>
                                    <h6 class="card-subtitle text-muted">${post.created_at}</h6>
                                </div>
                            </div>`
                        );
                    });

                    getPostUrl = responseData.links.next;

                    if  (initial === true) {
                        $('#dashboard').append(
                            `<div class="my-5 text-center" id="load-more">
                            <button class="btn btn-primary" onclick="loadPosts()">Load More</button>
                        </div>`
                        );
                        initial = false;
                    }
                },
                error: function (data) {
                    console.log(data)
                }
            });
        }
    </script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }} - @yield('title')</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('home') }}">Feeds</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('posts.create') }}">Create Post</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
</body>
</html>

resources/views/posts/comments/form.blade.php
<div class="mb-3">
    @if($commentId)
        <p class="btn-link reply_form_button_{{ $commentId }}"
           onclick="showReplyForm('{{ $commentId }}')">Add reply</p>
    @endif
    <div class="{{ $commentId ? 'd-none' : '' }} reply_form_{{ $commentId }}">
        <form action="{{ route('comments.store', ['post' => $post->id]) }}" method="post">
            @csrf
            <input type="hidden" name="parent_id" value="{{ $commentId }}">
            <textarea name="comment" class="form-control mb-1" id="" placeholder="Add reply"
                      rows="2" required></textarea>
            <button type="submit" class="btn btn-primary btn-sm">Reply</button>
        </form>
    </div>
</div>

resources/views/posts/comments/list.blade.php
@foreach($commentGroup as $comment)
    <div class="{{ $nested ? 'ml-4' : '' }}">
        <hr>
        <div class="mb-1">
            <p class="card-text">
                <a href="#" class="card-link mr-1">{{ $comment->user->name }}</a> {{ $comment->comment}}
            </p>
        </div>
        @include('posts.comments.form', ['commentId' => $comment->id])

        @isset($comments[$comment->id])
            @include('posts.comments.list', ['commentGroup' => $comments[$comment->id], 'nested' => true])
        @endisset
    </div>
@endforeach

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Create Post')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create Post</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('posts.store') }}"
                              enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Title {!! mandatory() !!}</label>

                                <div class="col-md-6">
                                    <input id="title" type="title"
                                           class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}"
                                           name="title" value="{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description"
                                       class="col-md-4 col-form-label text-md-right">Description {!! mandatory() !!}</label>

                                <div class="col-md-6">
                                    <textarea id="description" type="description"
                                              class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}"
                                              name="description" required>{{ old('description') }}</textarea>

                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="banner_image"
                                       class="col-md-4 col-form-label text-md-right">Banner Image {!! mandatory() !!}</label>

                                <div class="col-md-6">
                                    <div class="custom-file">
                                        <input type="file" id="banner-image"
                                               class="custom-file-input form-control{{ $errors->has('banner_image') ? ' is-invalid' : '' }}"
                                               name="banner_image" required>
                                        <label class="custom-file-label" for="banner-image">Choose file</label>
                                        @if ($errors->has('banner_image'))
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $errors->first('banner_image') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        $("#banner-image").change(function (e) {
            var $this = $(this);
            $this.next().html($this.val().split('\\').pop());
        });
    </script>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('title', 'Feeds')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8" id="dashboard">
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('error') }}
                    </div>
                @endif
                <div id="feeds">
                    <div class="card">
                        <img class="card-img-top" src="{{ $post->bannerImageUrl() }}" alt="Post banner image">
                        <div class="card-body">
                            <div class="mb-1" id="post-content">
                                <h5 class="card-title">{{ $post->title }}</h5>
                                <h6 class="card-subtitle mb-3"><a href="javascript:void(0)" class="card-link">{{ $post->user->name }}</a>
                                    <span class="card-subtitle text-muted">{{ $post->created_at->diffForHumans() }}</span>
                                </h6>
                                <p class="card-text">{{ $post->description }}</p>
                            </div>
                            @include('posts.comments.form', ['commentId' => null])
                            @include('posts.comments.list', ['commentGroup' => $comments['base'], 'nested' => false])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function showReplyForm(commentId) {
            $('.reply_form_'+commentId).removeClass('d-none');
            $('.reply_form_button_'+commentId).addClass('d-none');
        }
    </script>
@endsection